server:
  port: 10425

spring:
  datasource:
    url: jdbc:mysql://192.168.1.123:3306/wxh?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT
    username: wxh
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver